### ISSUE TITLE
Parsing best practices

### ISSUE THREAD

**Issue by DmitryAlCh** [ArturKarbone/CatalogScraper#1]
Have an object
company={
name: "These have nice tag addresses in document",
product: "So when parsing, you get one entry for one query",

person:"These have same tag and class adresses" 
phone:"so for 1 query you get a lot of entries (all needed , no trash)"

e-mail: "this entry has another addressation, the email is hidden inside tag definition"
}
So the methods of getting each of these 3 sets are different,
Should I make 3 parsing queries, with simple inside code, (then I need to combine 3 object in one obj)
or only 1 parsing query with "hard" logic, but one returned Object.?

**Comment by ArturKarbone** [comment]
@DmitryAlCh  parsing queries amount does not matter here. Just split the logic into small queries and compose the result out of them. 

like 
```
function companyBuilder()
{
	var buildProducts = () => {
		...
		return products
	}

	var buildContactPerson = () => {
		...
		return products
	}

	...

	return {
		products:buildProducts(),
		contactPerson: buildContactPerson()
 		 
	}
}```
