### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by DmitryAlCh** [ArturKarbone/CatalogScraper#3]
Is it necessary to make the actual navigation - perform a `click` event on a link -->
 then receive new page --> parse --> etc.
or just obtain `href` attribute value from `<a>` tag, 
and make request directly to the link.

**Comment by ArturKarbone** [comment]
Either way is good. At the end of the day you need a direct link to navigate. 

I still think we need navigation in some case like paging for instance or maybe we can hack this  playing with query string ?page=x or whatever parameter is used
